// Generated from features/*.feature for VSCode Cucumber step discovery.
// Do not hand-edit. Regenerate with: ./scripts/generate_cucumber_glue.sh
/* global Given, When, Then */

Given("\"gate_count_after\" is less than \"gate_count_before\"", function () {});
Given("CUDA runtime is unavailable", function () {});
Given("I apply CNOT from wire 0 to wire 1", function () {});
Given("I apply RX on wire 0 with theta \"0.3\"", function () {});
Given("I apply RY on wire 1 with theta \"0.1\"", function () {});
Given("I compute the same expectations using a scalar loop baseline", function () {});
Given("I estimate expectation with \"8192\" shots", function () {});
Given("I evaluate expectation before and after optimization", function () {});
Given("I measure expectation of Pauli-Z on wire 1", function () {});
Given("IR graph includes typed node metadata for register write", function () {});
Given("K is symmetric within tolerance \"1.0e-6\"", function () {});
Given("a batch input tensor x with shape \"{3,1}\" and values \"[0.0, 1.5707963267948966, 3.141592653589793]\"", function () {});
Given("a calibration matrix for readout mitigation", function () {});
Given("a circuit with 2 qubits", function () {});
Given("a circuit with redundant and cancelable gate sequences", function () {});
Given("a circuit with repeated adjacent single-qubit rotations", function () {});
Given("a conditional gate node controlled by classical register \"c0\"", function () {});
Given("a conditional gate references missing register \"c_missing\"", function () {});
Given("a deterministic feature-map circuit", function () {});
Given("a dynamic IR circuit containing classical branches", function () {});
Given("a fixed variational circuit topology", function () {});
Given("a hybrid Axon model with a classical dense preprocessor and a quantum_layer", function () {});
Given("a hybrid model with one classical dense layer and one quantum expectation head", function () {});
Given("a logical circuit with two-qubit gates", function () {});
Given("a loss function computing squared error to target \"1.0\"", function () {});
Given("a measurement node targeting classical register \"c0\"", function () {});
Given("a non-invertible or shape-mismatched calibration matrix", function () {});
Given("a non-native interaction is routed successfully", function () {});
Given("a one-qubit circuit where input x is encoded as theta = x", function () {});
Given("a one-qubit circuit with analytical expectation \"0.5\"", function () {});
Given("a one-qubit circuit with expectation observable Pauli-Z", function () {});
Given("a one-qubit circuit with ideal expectation \"1.0\"", function () {});
Given("a one-qubit variational circuit with RY(theta)", function () {});
Given("a parameterized quantum circuit with declared observables", function () {});
Given("a quantum circuit representing a state-vector simulation", function () {});
Given("a target topology coupling map is declared", function () {});
Given("a two-qubit circuit RX(theta_0) -> CNOT(0,1) -> RY(theta_1) is configured", function () {});
Given("an observable list \"[:pauli_x, :pauli_y, :pauli_z]\"", function () {});
Given("an unsupported observable identifier", function () {});
Given("batch size is \"1\"", function () {});
Given("batched parameters are provided as an Nx tensor", function () {});
Given("both modes should return finite scalar loss", function () {});
Given("computed gradients from both runs are exactly equal", function () {});
Given("conditional dependency is recorded in IR metadata", function () {});
Given("coupling map edges are \"[(0,1), (1,2), (2,3)]\"", function () {});
Given("coupling map edges are \"[(0,1), (1,3), (0,2), (2,3)]\"", function () {});
Given("dataset X with shape \"{16,4}\"", function () {});
Given("dataset X with shape \"{8,2}\"", function () {});
Given("dense preprocessor parameters are frozen and deterministic", function () {});
Given("depolarizing probability is \"0.1\"", function () {});
Given("deterministic execution mode is enabled", function () {});
Given("each profile includes an \"available\" capability flag from auto-detection", function () {});
Given("each run is reproducible when repeated with its own seed", function () {});
Given("error metadata includes available fallback \"cpu_compiled\"", function () {});
Given("error metadata includes expected and received shapes", function () {});
Given("error metadata includes matrix shape diagnostics", function () {});
Given("error metadata includes missing register identifier", function () {});
Given("error metadata includes offending logical edge", function () {});
Given("error metadata includes requested profile \"nvidia_gpu_compiled\"", function () {});
Given("error metadata includes target topology identifier", function () {});
Given("error metadata includes the invalid observable identifier", function () {});
Given("experimental dynamic-circuit IR mode is enabled", function () {});
Given("extrapolation metadata includes scale factors and fit diagnostics", function () {});
Given("fallback policy is \"allow_cpu_compiled\"", function () {});
Given("fallback policy is \"strict\"", function () {});
Given("first run seed is \"7\"", function () {});
Given("gradient mode \"<mode>\" is selected", function () {});
Given("gradient mode \"adjoint\" is selected", function () {});
Given("identical training data and optimizer configuration", function () {});
Given("inserted swaps are exactly \"[(0,1), (1,2)]\"", function () {});
Given("learning rate is \"0.1\"", function () {});
Given("loss is mean squared error over a single sample", function () {});
Given("message indicates dynamic execution is planned for a future release", function () {});
Given("mitigation pipeline \"[readout, zne_linear]\"", function () {});
Given("mitigation pipeline API is enabled", function () {});
Given("no circuit builder is provided", function () {});
Given("no custom gradient rules are required", function () {});
Given("noise scaling factors \"[1.0, 2.0, 3.0]\"", function () {});
Given("numerical tolerance is \"1.0e-4\"", function () {});
Given("numerical tolerance is \"1.0e-5\"", function () {});
Given("optimization report includes \"gate_count_after\"", function () {});
Given("optimizer is deterministic SGD with learning rate \"0.1\"", function () {});
Given("output expectation values should be approximately \"[1.0, 0.0, -1.0]\"", function () {});
Given("output includes per-pass trace metadata", function () {});
Given("output probability mass remains normalized within tolerance", function () {});
Given("output shape follows the batch contract", function () {});
Given("output shape matches the declared observable count", function () {});
Given("parameter tensor shape does not match circuit parameter schema", function () {});
Given("primitive output tensors from Sampler or Estimator", function () {});
Given("profiles are ordered by support tier priority", function () {});
Given("random seed is \"1234\"", function () {});
Given("random seed is \"2026\"", function () {});
Given("random seed is \"42\"", function () {});
Given("repeating generation with the same seed yields identical K", function () {});
Given("report includes \"depth_delta\"", function () {});
Given("report includes \"logical_to_physical_map\"", function () {});
Given("report includes \"routed_edges\"", function () {});
Given("report includes \"topology_id\"", function () {});
Given("restore_mapping policy is \"false\"", function () {});
Given("routed interaction edge becomes \"(2,3)\"", function () {});
Given("routing path \"[0,1,3]\" is selected deterministically", function () {});
Given("runtime profile \"<profile_id>\" is configured", function () {});
Given("runtime profile \"cpu_portable\" is configured", function () {});
Given("runtime profile \"nvidia_gpu_compiled\" is configured", function () {});
Given("runtime profile \"unknown_profile\" is configured", function () {});
Given("second run seed is \"99\"", function () {});
Given("seed is \"77\"", function () {});
Given("shot count is \"1024\"", function () {});
Given("shots is \"2048\"", function () {});
Given("shuffled batch order seed is \"42\"", function () {});
Given("strict and transpiled variants for a supported topology", function () {});
Given("target topology is \"all_to_all\"", function () {});
Given("target y is \"1.0\"", function () {});
Given("tensor operations are executed on the \"<target_hardware>\"", function () {});
Given("the circuit contains gate \"cnot(0,3)\"", function () {});
Given("the circuit includes an unsupported operation for adjoint mode", function () {});
Given("the default backend is set to \"<nx_backend>\"", function () {});
Given("the default compiler is set to \"<compiler>\"", function () {});
Given("the error includes the unsupported operation name", function () {});
Given("the error lists all supported runtime profile identifiers", function () {});
Given("the expectation operation is implemented as a pure tensor contraction", function () {});
Given("the logical circuit requires an unavailable coupling edge", function () {});
Given("the quantum_layer wraps a variational circuit with trainable theta offset", function () {});
Given("the register is produced earlier in the IR graph", function () {});
Given("the result includes metadata for runtime profile and execution mode", function () {});
Given("the supported runtime profiles are", function () {});
Given("the total sample count equals the configured shots", function () {});
Given("the training loss after the step is lower than before the step", function () {});
Given("theta is \"1.234\"", function () {});
Given("theta is a tensor with value \"1.5707963267948966\"", function () {});
Given("theta is a tensor with value \"<theta>\"", function () {});
Given("theta vector is \"[0.7, -0.3]\"", function () {});
Given("tie-break strategy \"lexicographic_path\" is applied", function () {});
Given("transpilation report added_swap_gates is \"0\"", function () {});
Given("transpilation report added_swap_gates is \"2\"", function () {});
Given("transpilation report routed_edges is empty", function () {});
Given("transpiler mode is \"insert_swaps\"", function () {});
Given("transpiler mode is \"strict\"", function () {});
Given("updated loss should be approximately \"0.6426439152043817\"", function () {});
Given("updated parameters from both runs are exactly equal", function () {});
Given("updated prediction should be approximately \"0.1986693307950612\"", function () {});
Given("updated theta should be approximately \"1.3707963267948966\"", function () {});
Given("warning code \"NXQ_BACKEND_FALLBACK_001\" is emitted", function () {});
Then("I receive a scalar tensor expectation value", function () {});
Then("I receive profile id, compiler, backend, hardware target, and support tier", function () {});
Then("K has shape \"{16,16}\"", function () {});
Then("batched and scalar results match within tolerance", function () {});
Then("both candidate shortest paths have length \"2\"", function () {});
Then("both estimates are exactly equal", function () {});
Then("both expectation outputs are identical within numeric tolerance", function () {});
Then("both expectations match within tolerance \"1.0e-5\"", function () {});
Then("both mitigated outputs are identical", function () {});
Then("both sampled batch outputs are identical", function () {});
Then("both sampled distributions are identical", function () {});
Then("corrected expectation is deterministic for fixed seed and inputs", function () {});
Then("each gradient component should match within \"1.0e-4\"", function () {});
Then("error \"adjoint_requires_circuit_builder\" is returned", function () {});
Then("error \"backend_unavailable\" is returned", function () {});
Then("error \"dynamic_execution_not_supported\" is returned", function () {});
Then("error \"invalid_batch_shape\" is returned", function () {});
Then("error \"invalid_dynamic_ir\" is returned", function () {});
Then("error \"invalid_mitigation_input\" is returned", function () {});
Then("error \"topology_violation\" is returned", function () {});
Then("error \"unsupported_gradient_mode\" is returned", function () {});
Then("error \"unsupported_observable\" is returned", function () {});
Then("error \"unsupported_runtime_profile\" is returned", function () {});
Then("execution uses the native \"<nx_backend>\" without custom backend routing", function () {});
Then("gradient for theta should be approximately \"2.0\"", function () {});
Then("initial parameters between runs are not equal", function () {});
Then("initial parameters from both runs are exactly equal", function () {});
Then("minimum eigenvalue of K is greater than or equal to \"-1.0e-6\"", function () {});
Then("no SWAP gate is inserted", function () {});
Then("noisy expectation absolute value is less than \"1.0\"", function () {});
Then("optimization report includes \"gate_count_before\"", function () {});
Then("output expectation tensor should have shape \"{3}\"", function () {});
Then("output values match scalar API values", function () {});
Then("pass execution order matches the declared pipeline order", function () {});
Then("report includes \"added_swap_gates\"", function () {});
Then("routing path \"[0,1,2,3]\" is selected", function () {});
Then("runtime profile \"cpu_compiled\" is selected", function () {});
Then("the \"8192\"-shot estimate is closer to \"0.5\" than the \"128\"-shot estimate", function () {});
Then("the expectation tensor should have value approximately \"<expected_expectation>\"", function () {});
Then("the gradient should be approximately \"<expected_gradient>\"", function () {});
Then("the optimized expectation matches the original within tolerance", function () {});
Then("the output tensor preserves the input observable order", function () {});
Then("the quantum parameters are updated deterministically", function () {});
Then("validation succeeds", function () {});
When("I apply H on wire 0", function () {});
When("I apply ZNE linear extrapolation", function () {});
When("I apply readout mitigation", function () {});
When("I apply readout mitigation twice to the same input", function () {});
When("I compile the expectation function for the circuit", function () {});
When("I compute expectations in batched mode", function () {});
When("I compute gradients", function () {});
When("I compute gradients with adjoint and parameter_shift", function () {});
When("I compute the gradient of expectation loss with respect to theta", function () {});
When("I estimate expectation by shots twice", function () {});
When("I estimate expectation with \"128\" shots", function () {});
When("I evaluate expectation of Pauli-Z on wire 0 within defn", function () {});
When("I evaluate expectation of Pauli-Z within defn", function () {});
When("I evaluate expectation on both circuits in simulation", function () {});
When("I evaluate expectation with depolarizing noise", function () {});
When("I evaluate the expectation within defn", function () {});
When("I execute the pipeline", function () {});
When("I generate the kernel matrix K for X", function () {});
When("I inspect the transpilation report", function () {});
When("I optimize the circuit with passes \"fuse,cancel\"", function () {});
When("I optimize the circuit with passes \"simplify,fuse,cancel\"", function () {});
When("I request runtime execution", function () {});
When("I request the gradient of the loss with respect to theta using Nx.grad", function () {});
When("I request the runtime profile catalog", function () {});
When("I run a single Estimator request with that observable list", function () {});
When("I run batched Estimator", function () {});
When("I run batched Sampler twice", function () {});
When("I run batched execution", function () {});
When("I run exactly one SGD step", function () {});
When("I run one Axon.train_step on identical seeded setup", function () {});
When("I run one training step for each seed from a clean state", function () {});
When("I run one training step twice from a clean state", function () {});
When("I run the Estimator primitive", function () {});
When("I run the Estimator primitive twice with the same parameters and seed", function () {});
When("I run the Sampler primitive twice with the same shots and seed", function () {});
When("I run transpilation", function () {});
When("I run transpilation on the logical circuit", function () {});
When("I validate dynamic IR", function () {});
